server:
  port: 8761
spring:
  application:
    name: discovery-service
  boot:
    admin:
      client:
        url: http://44.215.126.0:8888/admin
        instance:
          service-base-url: http://44.215.126.0:8888/admin
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://3.238.58.112:8761/eureka