eureka:
  client:
    service-url:
      defaultZone: http://3.238.58.112:8761/eureka
server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  main:
    web-application-type: reactive