server:
  port: 8761
spring:
  application:
    name: discovery-service
  boot:
    admin:
      client:
        url: http://34.205.135.13:8888/admin
        instance:
          service-base-url: http://34.205.135.13:8888/admin
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://34.206.1.209:8761/eureka